/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gamesforyou;

/**
 *
 * @author Matheus
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        IconHome = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        IconBag = new javax.swing.JLabel();
        Estoque = new javax.swing.JLabel();
        IconLista = new javax.swing.JLabel();
        Usuarios = new javax.swing.JLabel();
        IconVenda = new javax.swing.JLabel();
        Vendas = new javax.swing.JLabel();
        IconRela = new javax.swing.JLabel();
        Relatorios = new javax.swing.JLabel();
        IconPerson = new javax.swing.JLabel();
        PessoaLog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Home.setBackground(new java.awt.Color(238, 242, 246));
        Home.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 139, 248), 2, true));

        Menu.setBackground(new java.awt.Color(66, 139, 248));

        IconHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\Matheus\\Downloads\\home_FILL0_wght400_GRAD0_opsz24 1.png")); // NOI18N

        Inicio.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.setText("Inicio");

        IconBag.setIcon(new javax.swing.ImageIcon("C:\\Users\\Matheus\\Downloads\\shopping_bag_FILL0_wght400_GRAD0_opsz24 1.png")); // NOI18N

        Estoque.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        Estoque.setForeground(new java.awt.Color(255, 255, 255));
        Estoque.setText("Estoque");

        IconLista.setIcon(new javax.swing.ImageIcon("C:\\Users\\Matheus\\Downloads\\patient_list_FILL0_wght400_GRAD0_opsz24 1.png")); // NOI18N

        Usuarios.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        Usuarios.setText("Usuarios");

        IconVenda.setIcon(new javax.swing.ImageIcon("C:\\Users\\Matheus\\Downloads\\monetization_on_FILL0_wght400_GRAD0_opsz24 1.png")); // NOI18N

        Vendas.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        Vendas.setForeground(new java.awt.Color(255, 255, 255));
        Vendas.setText("Vendas");

        IconRela.setFont(new java.awt.Font("Anta", 0, 12)); // NOI18N
        IconRela.setIcon(new javax.swing.ImageIcon("C:\\Users\\Matheus\\Downloads\\monitoring_FILL0_wght400_GRAD0_opsz24 1.png")); // NOI18N

        Relatorios.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        Relatorios.setForeground(new java.awt.Color(255, 255, 255));
        Relatorios.setText("Relatorios");

        IconPerson.setIcon(new javax.swing.ImageIcon("C:\\Users\\Matheus\\Downloads\\person_FILL0_wght400_GRAD0_opsz24 1.png")); // NOI18N

        PessoaLog.setFont(new java.awt.Font("Anta", 0, 36)); // NOI18N
        PessoaLog.setForeground(new java.awt.Color(255, 255, 255));
        PessoaLog.setText("Nome Pessoa Logada");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(IconHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inicio)
                .addGap(91, 91, 91)
                .addComponent(IconBag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Estoque)
                .addGap(123, 123, 123)
                .addComponent(IconLista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Usuarios)
                .addGap(122, 122, 122)
                .addComponent(IconVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Vendas)
                .addGap(109, 109, 109)
                .addComponent(IconRela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Relatorios)
                .addGap(100, 100, 100)
                .addComponent(IconPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PessoaLog)
                .addGap(19, 19, 19))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PessoaLog)
                    .addComponent(IconPerson)
                    .addComponent(Inicio)
                    .addComponent(IconHome)
                    .addComponent(IconBag)
                    .addComponent(Estoque)
                    .addComponent(IconLista)
                    .addComponent(Usuarios)
                    .addComponent(Vendas)
                    .addComponent(IconVenda)
                    .addComponent(Relatorios)
                    .addComponent(IconRela))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 944, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Estoque;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel IconBag;
    private javax.swing.JLabel IconHome;
    private javax.swing.JLabel IconLista;
    private javax.swing.JLabel IconPerson;
    private javax.swing.JLabel IconRela;
    private javax.swing.JLabel IconVenda;
    private javax.swing.JLabel Inicio;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel PessoaLog;
    private javax.swing.JLabel Relatorios;
    private javax.swing.JLabel Usuarios;
    private javax.swing.JLabel Vendas;
    // End of variables declaration//GEN-END:variables
}
